site_name: "sway-out"

theme:
  name: "material"
  features:
    - content.code.copy

plugins:
  - autorefs
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - sway-out: index.md
  - Reference:
    - sway_out.applications: reference/sway_out.applications.md
    - sway_out.connection: reference/sway_out.connection.md
    - sway_out.layouts: reference/sway_out.layouts.md
    - sway_out.main: reference/sway_out.main.md
    - sway_out.matching: reference/sway_out.matching.md
